#Creando diccionario, claves dni y valor el nombre de la persona
dni = {5766552 : 'Maria', 698755 : 'Lorena', 987746 : 'Josefa', 8875562 : 'Antonio', 66554 : 'David'}
print (dni[698755])

#Creando diccionario 2, claves autogenerdas
telefonos = {'Maria' : 15765852, 'Lorena' : 15822655, 'Antonio' : 35125555, 'David' : 3512887454}
print(telefonos.keys())
print(telefonos.values())
print(telefonos.items())